events {}

http {
    include /etc/nginx/mime.types;

    server {
        listen 80;

        location /api/v1/auth {
            proxy_pass http://user-service:8000;
        }

        location /api/v1/users {
            proxy_pass http://user-service:8000;
        }

        location /api/v1/products {
            proxy_pass http://product-service:8000;
        }

        location /api/v1/categories {
            proxy_pass http://product-service:8000;
        }

        location /api/v1/orders {
            proxy_pass http://order-service:8000;
        }

        location /api/v1/payments {
            proxy_pass http://payment-service:8000;
        }

        location /api/v1/notifications {
            proxy_pass http://notification-service:8000;
        }

        location /healthz {
            return 200 "ok\n";
        }
    }
}
